port: zephyr: Fix log undefined reference
z_log_msg_runtime_vcreate is not defined when using minimal log, we
need to check it in the build to avoid undefined reference to this
symbol.

Signed-off-by: Flavio Ceolin <flavio@hubblenetwork.com>